#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso DPMrsmwhTurbulenceModels

wclean
wclean MPPICrsmwhFoam
#wclean DPMDyMFoam
#wclean DPMDyMFoam/MPPICDyMFoam

#------------------------------------------------------------------------------
