#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Create gear0 mesh using cfMesh
( cd gear0 && ./Allrun )

# Create gear1 mesh using cfMesh
( cd gear1 && ./Allrun )

( cd case_overset && ./Allrun )

#------------------------------------------------------------------------------
