#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#rm -f constant/triSurface/cyclone.stl.gz > /dev/null 2>&1

cleanCase
# rm -rf processor*
# rm -rf log.decomposePar
# rm -rf log.moveMesh
# rm -rf log.renumberMesh

#------------------------------------------------------------------------------
